{% set name = "nansat" %}
{% set version = "1.0.16" %}
{% set sha256 = "83da86e16f69d188eb6e385c3fe2cb92016073765190460ef8464def7836d3ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
 fn: v{{ version }}.tar.gz
 url: https://github.com/nansencenter/nansat/archive/v{{ version }}.tar.gz
 sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - pythesint 1.4.5
    - numpy 1.14.5
    - scipy 1.1.0
    - matplotlib 2.2.2
    - basemap 1.1.0
    - netcdf4 1.4.0
    - gdal 2.2.4
    - pillow 5.1.0
  run:
    - python
    - pythesint >=1.4.5
    - numpy >=1.14.5
    - scipy 1.1.0
    - matplotlib >=2.2.2
    - basemap >=1.1.0
    - netcdf4 >=1.4.0
    - gdal >=2.2.4
    - pillow >=5.1.0

test:
  requires:
    - mock
    - nose
  commands:
    - nosetests nansat

about:
  home: https://github.com/nansencenter/nansat
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Nansat is a scientist friendly Python toolbox for processing 2D satellite earth observation data.'

  description: |
    The main goal of Nansat is to facilitate:
    easy development and testing of scientific algorithms,
    easy analysis of geospatial data, and
    efficient operational processing.
    We appreciate acknowledments of Nansat.
    Please add "The image analysis was performed with the open-source
    Nansat (https://github.com/nansencenter/nansat) python package"
    (or equivalent) if you use Nansat in scientific publications.
  doc_url: http://nansat.readthedocs.io/
  dev_url: https://github.com/nansencenter/nansat

extra:
  recipe-maintainers:
    - aleksandervines
    - akorosov
