travis:
  secure:
    BINSTAR_TOKEN: DOc8OqZLucpnd/UCJ+qdW2p2nWx8aNCyo9eUXJSIg/ypMy2ECUyvh2IlfkY9XzfWQg2+zjF2o9Oj93OLB0kFTANj2gpXMq4u8nzIN3XtjqRncqdT2S0z4e9ntQj2cY2ixZqBKlhkz6v0+bjE2RwS9NwfRwkzWSYivlcKQOJ+mZsGSexKQjCPefrUBHgFpnRXwV4b5ySxwspkfjEUoYMPvXdzbhSen4cnMnNH5Yl4cvAvMc/CEq92uZXAu/Gu4q9maTCHISv77YZ2TztmeCzQjFY3LC7wicT0eYQBq7o7bPQobSgKJ8Tmo/SsE4jBo3GXLYKyMq3EEqoT/xWpnKctTM8dJWrMS6TTIJchydPgcozkUS8Hgae0JoEm+JysB3AYmsSR8aPB5AM3nInleRuDL6xi+SnVJW0sDLpDo4xGGRNDgjX/o8QTk0LojyK0qEt0pKvvQ8R8Zp/F6187HjfBwavKAA6kvUYKz75Jo18v0IsfI40IDUAjaLjBbIe+Kv+/WuWfspSfWPorotQAqpvXmW//Q5P9PdcUVrTKDZglIcxCvdbnp0fnMRdKhkyv0CNoIKa3njNtq73MwBfWzjJZI2H/M6jkh4Wnr6bLArnjMtxfw9ZOndwqho57vHyZDoIOf4BNHA5uiIxnBnh2jQ1xWn6N/0rCTBpZ3juqJbwHcXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
